# in _config.yml
title: "Introduction to Data Science for Engineers"
author: John M. Shea
copyright: "2021"
only_build_toc_files: true
#logo: images/logo.png
execute:
  execute_notebooks: "off"
parse:
  myst_enable_extensions: 
    - amsmath
    - colon_fence
    - deflist
    - dollarmath
    - html_admonition
    - linkify
    - smartquotes
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

